db:
  image: 'mysql:5.6.45'
  container_name: 'timeoff_db'
  restart: unless-stopped
  ports:
    - 3308:3306
  # volumes:
  #   - ./volumes/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=timeoff
    - MYSQL_DATABASE=timeoff
    - MYSQL_USER=timeoff
    - MYSQL_PASSWORD=timeoff

app:
  image: thperret/timeoff-management:0.6.2
  container_name: 'timeoff_app'
  links:
    - db:db
  restart: unless-stopped
  # volumes:
  #   - ./volumes/config:/opt/timeoff-management/config
  ports:
    - '3000:3000'
  environment:
    - ALLOW_ACCOUNTS_CREATION=true  # set this to false to disable public account creation (set it once you have created your company to disable public regitration)
    # - APP_URL=https://timeoff.example.com
    # - PROMOTION_URL=https://timeoff.example.com # uncomment and set this if you want to use you URL for footer promotion url
    - NODE_ENV=production
    # - SENDER_MAIL=timeoff@example.com # only set this if you want mail support
    # - SMTP_HOST=127.0.0.1
    # - SMTP_PORT=25
    # - SMTP_USER=timeoff
    # - SMTP_PASSWORD=timeoff
    - MYSQL_HOST=db
    - MYSQL_USER=timeoff
    - MYSQL_DATABASE=timeoff
    - MYSQL_PASSWORD=timeoff